name: sequana_variant_calling

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - freebayes>1
  - bwa
  - 'snpeff==5.1d'
  - sambamba
  - picard>2.26
  - samtools>=1.15
  - bamtools
  - pip
  - pip:
    - sequana


